// About/index.jsx
// import React from 'react'
import {Icon} from 'zarm'
import s from './style.module.less'
const MyIcon = Icon.createFromIconfont('//lf1-cdn-tos.bytegoofy.com/obj/iconpark/svg_20337_14.627ee457cf7594fbbce6d5e14b8c29ef.js'); // generated by iconfont.cn
const Home = () => {
  return (
   <div className={s.home}>
    <div className={s.header}>
      <div className={s.dataWrap}>
        <span className={s.expense}>总支出：<b>¥ 200</b></span>
        <span className={s.income}>总收入：<b>¥ 500</b></span>
      </div>
      <div className={s.typeWrap}>
        <div className={s.left}>
          <span className={s.title}>类型 <MyIcon className={s.arrow} type="home" /></span>
        </div>
        <div className={s.right}>
          <span className={s.time}>2022-06<MyIcon className={s.arrow} type="home" /></span>
        </div>
      </div>
    </div>
  </div>
  )
}

export default Home